name: CI

on: [push,pull_request,workflow_dispatch]

jobs:
  build:

    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: |
        set -o pipefail && xcodebuild -list -workspace ShadowsocksX-NG.xcworkspace
        xcodebuild -list -project ShadowsocksX-NG.xcodeproj
        xcodebuild clean build -workspace ShadowsocksX-NG.xcworkspace -scheme ShadowsocksX-NG|xcpretty
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: /Users/runner/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-feziwapglahwzfdugdielljnexfv/Build/Products
