name: CI

on: [push,pull_request,workflow_dispatch]

jobs:
  build:

    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v1
    - name: Run unit test
      run: |
        set -o pipefail && xcodebuild test -workspace ShadowsocksX-NG.xcworkspace -scheme ShadowsocksX-NG|xcpretty
